<a href="https://colab.research.google.com/github/taehi5/Esaa_YB/blob/Week1/ESAA_YB_Week1_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [33]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [34]:
# __: 던더
# __version__ : 넘파이 모듈의 속성
print(np.__version__)

# np안에 있는 show_config라는 함수를 호출()한다.
# 빌드 설정(컴파일러, blas 등) 확인
np.show_config()

2.1.3
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.13.0/lib/python3.13/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.13.0/lib/python3.13/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.13.0/lib/python3.13/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.13.0/lib/python3.13/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: ld.bfd


#### 3. Create a null vector of size 10 (★☆☆)

In [35]:
zero_array = np.zeros(10)
print(zero_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [76]:
array = np.zeros((10,10))
# size: 전체 원소 개수(100)
# itemsize: 원소 하나가 차지하는 byte 수(8)
# 전체 메모리(원소 개수 * 원소 하나의 크기) : 100*8=800
print(array.size, array.itemsize)
print("%d bytes" % (array.size * array.itemsize))
# 메모리 사이즈를 바로 구하는 속성
print('메모리 사이즈:',array.nbytes)

100 8
800 bytes
메모리 사이즈: 800


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [37]:
array = np.zeros(10)
# index 4가 다섯번째 값
array[4] = 1
print(array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [38]:
array = np.arange(10,50)
print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [39]:
array = np.arange(10)
print('원본:', array)

# 슬라이싱 step을 -1로 주면 거꾸로 읽음
reverse_array = array[::-1]
print('뒤집은 배열:', reverse_array)

원본: [0 1 2 3 4 5 6 7 8 9]
뒤집은 배열: [9 8 7 6 5 4 3 2 1 0]


#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [40]:
array = np.arange(9)
matrix = array.reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [41]:
array = [1,2,0,0,4,0]
# 0이 아닌 원소들의 index를 반환
index = np.nonzero(array)
print(index)

(array([0, 1, 4]),)


#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [42]:
#eye : 행과 열의 개수를 다르게 지정하거나 대각선 위치를 이동할 수 있는 단위 행렬
#identity : 정사각형 단위행렬만 생성함
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [43]:
random_array = np.random.random((3,3,3))
print(random_array)

[[[0.05276503 0.02771394 0.05678532]
  [0.72149686 0.95307231 0.7452144 ]
  [0.75863143 0.34542069 0.41107171]]

 [[0.84340771 0.32641137 0.43678626]
  [0.7333318  0.64652674 0.56401682]
  [0.42699507 0.57267816 0.3737816 ]]

 [[0.5714613  0.3404966  0.19315683]
  [0.99013685 0.46850004 0.34962427]
  [0.73353242 0.789572   0.77324615]]]


#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [44]:
random_array = np.random.random((10,10))
print(random_array)

min_value = random_array.min()
max_value = random_array.max()
print('최솟값:', min_value, '최댓값:', max_value)

[[6.17453626e-01 3.69677898e-01 3.73977743e-01 8.54321449e-01
  3.48903664e-01 3.89465237e-01 8.57287601e-01 8.09656744e-03
  9.57911217e-01 6.52331742e-01]
 [4.09998020e-01 2.06418419e-02 3.97663411e-01 8.31965556e-01
  2.00831459e-04 8.87574522e-01 3.19496219e-01 7.97209544e-01
  6.52359016e-01 2.11385591e-01]
 [4.43801997e-01 4.60916118e-01 8.02611856e-01 5.80186866e-01
  2.17169578e-01 6.36863209e-01 2.41089673e-01 7.40088816e-01
  7.75311734e-01 6.03679021e-01]
 [3.42732361e-01 4.75144347e-01 9.72572883e-01 1.41057343e-01
  3.91889192e-01 4.15383436e-01 6.49291324e-01 2.74403759e-01
  5.30632828e-01 7.85149034e-01]
 [3.23016761e-01 9.99033711e-01 2.53978626e-01 5.33664934e-01
  7.52674602e-01 8.73498042e-01 5.03956686e-02 8.68075784e-01
  4.23725672e-01 7.55333937e-01]
 [9.63793009e-03 1.18497952e-01 6.45928021e-02 9.43255087e-01
  8.76167128e-01 3.52958670e-01 5.84193703e-01 9.37355629e-01
  3.74881662e-01 1.56036800e-01]
 [1.86585802e-01 9.93849612e-02 6.78026271e-01 6.99640338e

#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [45]:
random_array = np.random.random(30)
mean_value = random_array.mean()
print('평균값:', mean_value)

평균값: 0.4990885473030523


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [46]:
#테두리는 1, 내부는 0인 2차원 배열 생성하기
array = np.ones((10,10))
# array[행,열] ->  첫번째 1:-1은 첫 행과 마지막 행을 제외한 행, 두번째 1:-1은 첫 열과 마지막 열을 제외한 열
# => 가운데 부분만 골라서 0으로 채움
array[1:-1, 1:-1] = 0
print(array)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [47]:
# 다른 방법 : np.pad로 0으로 채운 폭 1의 테두리를 둘러싸기
inner = np.zeros((8,8))
array2 = np.pad(inner, pad_width=1, mode='constant', constant_values=1)
print(array2)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```


1. nan: np.nan을 사용, 결과도 nan(주로 실수 연산에서 정의 x, 누락된 값)
* na : not available, 값이 없다. 주로 판다스에서 제공
2. False: nan은 자기자신과 같지 않음 -> 결측값 확인 시 np.isnan 사용
3. False: nan자체가 비교 가능한 숫자가 x
4. nan: 정상적인 수치 연산 x
5. True: 동일한 np.nan객체를 집합에 넣고 다시 찾음
6. False : 컴퓨터에서 부동소수점은 이진수로 근사되어 정확하게 저장 x

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [48]:
# k=-1 이면 대각선 바로 아래쪽에 값을 채움
matrix = np.diag([1,2,3,4], k=-1)
print(matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [49]:
matrix = np.zeros((8,8), dtype=int)
# 홀수 행의 짝수 열, 짝수 행의 홀수 열에 1을 채우면 체스판 무늬가 됨
matrix[1::2, ::2] = 1
matrix[::2, 1::2] = 1
print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [50]:
# unravel:한줄로 펼친 인덱스99를 3차원 좌표로 변환해 주는 함수
# 100번째 원소 -> value = 99
index = np.unravel_index(99, (6,7,8))
print(index)

(np.int64(1), np.int64(5), np.int64(3))


#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [51]:
matrix = np.random.random((5,5))
mean = matrix.mean()
std = matrix.std()
normalized = (matrix - mean) / std
print(normalized)

[[-1.59305284  0.23107931 -1.75024811 -1.2118534   1.23528851]
 [ 1.09821357 -0.2557692   0.19891328  0.47497945  0.51493344]
 [ 0.51642022 -0.83898798  0.42003766  1.26576412  1.50292362]
 [-1.40513854 -0.82849911 -1.26062623  1.15465036  1.25664742]
 [-0.73468359  0.3812689   0.50782413  0.28398806 -1.16407305]]


#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [52]:
# (r,np.ubyte): r -> 필드 이름, np.ubyte->해당 필드의 자료형
color_dtype = np.dtype([('r', np.ubyte),
                         ('g', np.ubyte),
                         ('b', np.ubyte),
                         ('a', np.ubyte)])
print(color_dtype)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [53]:
A = np.ones((5,3))
B = np.ones((3,2))
result = np.dot(A,B)
print(result)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [54]:
result2 = A @ B
print(result2)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [55]:
array = np.arange(11)
print('원본:', array)

array[(array > 3) & (array < 8)] *= -1
print('변경 후:', array)

원본: [ 0  1  2  3  4  5  6  7  8  9 10]
변경 후: [ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

* Python 내장 sum: sum(반복가능한 값, 시작값)이므로 <br>(range(5), -1)은 0+1+2+3+4-1이므로 결과가 `9`이다.
* NumPy의 `sum`: 두 번째 인수 `-1`은 시작값이 아니라 마지막 축을 의미한다. 1차원 배열에서 `axis=-1`은 유효하므로 결과가 `10`이다.

따라서 출력은 다음과 같다.

```text
9
10
```

#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [56]:
Z = np.arange(5)

print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
# print(Z<Z>Z) ->에러

[  1   1   4  27 256]
[0 1 2 4 8]
[False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]
[0. 1. 2. 3. 4.]


#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [57]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/tmp/ipykernel_2035/3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
/tmp/ipykernel_2035/3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
/tmp/ipykernel_2035/3912170336.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [58]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print('Z1:', Z1)
print('Z2:', Z2)

# 두 배열에 공통으로 들어있는 값만 뽑아줌
common = np.intersect1d(Z1,Z2)
print('공통값:', common)

Z1: [6 9 7 0 6 4 1 6 1 8]
Z2: [1 2 5 1 3 7 9 3 4 8]
공통값: [1 4 7 8 9]


#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [59]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


/tmp/ipykernel_2035/2770867030.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1) == np.emath.sqrt(-1))


#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [60]:
dates = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [61]:
A = np.ones(3)*1
B = np.ones(3)*2

# out 파라미터를 쓰면 새로 배열을 만들지 않고 그 자리에서 계산됨
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)
print(A)

[-1.5 -1.5 -1.5]


#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [62]:
array = np.random.uniform(0,10,10)
print('원본:', array)

# 방법1 : 나머지를 빼기
method1 = array - array%1
print('방법1:', method1)

# 방법2 : 몫 연산자 //
method2 = array // 1
print('방법2:', method2)

원본: [3.33599589 4.07608084 2.54748011 9.70703413 3.12097053 7.3792893
 4.09248843 0.98880147 7.11166887 1.5137335 ]
방법1: [3. 4. 2. 9. 3. 7. 4. 0. 7. 1.]
방법2: [3. 4. 2. 9. 3. 7. 4. 0. 7. 1.]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [63]:
matrix = np.zeros((5,5))
matrix += np.arange(5)
print(matrix)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 32. Create a random vector of size 10 and sort it (★★☆)

In [64]:
array = np.random.random(10)
print('정렬 전:', array)
array.sort()
print('정렬 후:', array)

정렬 전: [0.8492371  0.32208895 0.53232455 0.60210948 0.93348104 0.66111537
 0.63947239 0.37156097 0.02322371 0.33986497]
정렬 후: [0.02322371 0.32208895 0.33986497 0.37156097 0.53232455 0.60210948
 0.63947239 0.66111537 0.8492371  0.93348104]


#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [65]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
print('A:', A)
print('B:', B)

is_equal = np.array_equal(A,B)
print('두 배열이 같은가?', is_equal)

A: [1 0 1 1 0]
B: [1 1 0 1 1]
두 배열이 같은가? False


#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [66]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]

# 원점에서부터의 거리
R = np.sqrt(X**2 + Y**2)
# x축 기준 각도
T = np.arctan2(Y,X)
print('거리:', R)
print('각도:', T)

거리: [0.90003772 0.16705395 0.871632   0.69694815 0.68517181 0.97351192
 0.78842673 0.75796278 1.036673   0.7246696 ]
각도: [1.49952655 1.10386644 0.56682302 1.14236175 1.42395666 0.24334681
 1.3752247  1.03849338 1.29153555 0.35242815]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [67]:
array = np.random.random(10)
print('원본:', array)

# argmax()로 최댓값의 index를 찾아서 그 자리를 0으로 바꿔줌
array[array.argmax()] = 0
print('변경 후:', array)

원본: [0.18007657 0.12412975 0.79789177 0.23016981 0.72681372 0.555462
 0.14745009 0.66103878 0.43145662 0.40887957]
변경 후: [0.18007657 0.12412975 0.         0.23016981 0.72681372 0.555462
 0.14745009 0.66103878 0.43145662 0.40887957]


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [68]:
Z = np.arange(100)
v = np.random.uniform(0,100)
print('v:', v)

# v와 각 원소의 차이의 절댓값이 가장 작은 index를 찾음
index = (np.abs(Z-v)).argmin()
print('가장 가까운 값:', Z[index])

v: 42.85296343462943
가장 가까운 값: 43


#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [69]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [70]:
n = 10
p = 3
Z = np.zeros((n,n))
# n*n개의 자리 중 p개를 중복없이 뽑아서 1을 채움
Z.put(np.random.choice(range(n*n), p, replace=False), 1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [71]:
array_3x3 = np.random.randint(0,10,(3,3))
print('원본:\n', array_3x3)

# column 3 (index 2) 기준으로 argsort한 순서대로 행을 재배열
print('column 3 기준 정렬:\n', array_3x3[array_3x3[:,2].argsort()])

원본:
 [[6 5 7]
 [3 7 4]
 [4 2 4]]
column 3 기준 정렬:
 [[3 7 4]
 [4 2 4]
 [6 5 7]]


In [72]:
# column 2 (index 1) 기준
print('column 2 기준 정렬:\n', array_3x3[array_3x3[:,1].argsort()])

column 2 기준 정렬:
 [[4 2 4]
 [6 5 7]
 [3 7 4]]


In [73]:
# column 1 (index 0) 기준
print('column 1 기준 정렬:\n', array_3x3[array_3x3[:,0].argsort()])

column 1 기준 정렬:
 [[3 7 4]
 [4 2 4]
 [6 5 7]]
