<a href="https://colab.research.google.com/github/taehi5/Esaa_YB/blob/1%EC%A3%BC%EC%B0%A8-%EA%B3%BC%EC%A0%9C/ESAA_YB_Week1_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


>  파이썬 머신러닝 완벽 가이드 ch1. p.1~38 필사



# Chapter 1. 파이썬 기반의 머신러닝과 생태계 이해






## **01. 머신러닝의 개념**
 머신러닝(Machine Learning) : 데이터를 기반으로 패턴을 학습하고 결과를 예측하는 알고리즘 기법을 통칭


*   소프트웨어 코드로 로직을 구성, 이들을 관통하는 일정한 패턴을 찾기 어려운 경우 -> 머신러닝이 훌륭한 솔루션 제공
*   데이터를 기반으로 통계적인 신뢰도 강화, 예측 오류를 최소화하기 위한 다양한 수학적 기법 적용 , 데이터 내의 패턴을 스스로 인지하고 신뢰도 있는 예측 결과 도출

### 1) 머신러닝의 분류
*  지도 학습: 분류, 회귀 등
*  비지도 학습: 클러스터링, 차원 축소
*  강화학습

### 2) 데이터 전쟁
머신러닝의 단점: 데이터에 의존적
<br>데이터를 이해, 효율적으로 가공, 처리, 추출 -> 최적의 데이터를 기반으로 알고리즘을 구동할 수 있도록 준비하는 능력이 더 중요

### 3) 파이썬 vs R
파이썬: 직관적인 문법과 객체지향과 함수형 프로그래밍 모두를 포괄하는 유연한 프로그램 아키텍처
<br>R: 통계 전용 프로그램 언어


## **02. 파이썬 머신러닝 생태계를 구성하는 주요 패키지**
### 1) 머신러닝 패키지
*   Scikit-Learn:데이터 마이닝 기반의 머신러닝 패키지
*   Tensorflow, Keras: 전문 딥러닝 라이브러리
### 2) 행렬/선형대수/통계 패키지
*   Numpy: 행렬과 선형대수 관련 패키지
*   SciPy: 자연과학과 통계를 위한 다양한 패키지
### 3) 데이터 핸들링
*   Pandas: 2차원 데이터 처리에 특화되어 Numpy보다 데이터 처리가 편리, Matplotlib을 호출해 시각화 쉬움
### 4) 시각화
*   Matplotlib: 파이썬의 대표적인 시각화 패키지
*   Seaborn: matplotlib을 보완하기 위한 시각화 패키지
### 5) Jupyter Notebook: 대표적인 대화형 파이썬 툴

## **파이썬 머신러닝을 위한 S/W 설치 (교재 p.7~12)**

### 1) Anaconda 설치
* 파이썬 머신러닝에 필요한 넘파이, 판다스, 맷플롯립, 시본, 주피터 노트북 등의 패키지를 한 번에 설치할 수 있다.
* Anaconda Individual Edition을 내려받아 설치하며, 설치 후 Anaconda Prompt와 Jupyter Notebook을 사용할 수 있다.
* Anaconda Prompt에서 `python -V`를 실행해 파이썬 버전을 확인한다.

### 2) 주요 패키지 설치 확인
주피터 노트북에서 다음 패키지를 임포트했을 때 오류가 발생하지 않으면 정상적으로 설치된 것이다.

```python
import numpy
import pandas
import matplotlib.pyplot
import seaborn
from sklearn.model_selection import train_test_split
```

### 3) Microsoft Visual Studio Build Tools 설치
* 윈도우에서 LightGBM, Surprise 등 일부 서드파티 패키지를 설치하려면 Microsoft Visual Studio Build Tools가 필요할 수 있다.
* Visual Studio Build Tools 설치 화면에서 **C++를 사용한 데스크톱 개발** 워크로드를 선택해 설치한다.


## **03.넘파이**
: 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 대표적인 패키지
*   루프 사용 x, 대량 데이터의 배열 연산 가능 => 빠른 배열 연산 속도 보장
*   저수준 언어 기반의 호환 API 제공: 기존 c/c++기반의 타 프로그램과 데이터를 주고받거나 API를 호출해 쉽게 통합할 수 있는 기능 제공
*   다양한 데이터 핸들링 기능 제공




### 1) 넘파이 ndarray 개요
*  넘파이의 기반 데이터 타입 : ndarray
*  ndarray를 이용해 넘파이에서 다차원 배열을 쉽게 생성, 다양한 연산 수행 가능

In [ ]:
# 넘파이 모듈 임포트
import numpy as np

넘파이 array 함수: 파이썬의 리스트와 같은 다양한 인자 입력, ndarray로 변환하는 기능
*   ndarray로 변환을 원하는 객체를 인자로 입력하면 ndarray로 반환
*   ndarray.shape: ndarray의 차원과 크기를 tuple 형태로 나타냄<br>ex) [1,2,3]이면 (3,): 1차원 array로 3개의 데이터를 가지고 있음

In [ ]:
array1 = np.array([1,2,3])
print('array1 type:', type(array1))
print('array1 array 형태:',array1.shape)

array2 = np.array([[1,2,3],
                   [2,3,4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)

array3 = np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [ ]:
# ndarray.ndim이용해 array 차원 확인
print('array1: {0}차원, array2:{1}차원, array3:{2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1: 1차원, array2:2차원, array3:2차원


### 2) ndarray의 데이터 타입
*   ndarray내의 데이터 값은 숫자 값, 문자열 값, 불 값 등 모두 가능
*   ndarray내의 데이터 타입은 그 연산의 특성상 같은 데이터 타입만 가능
*   한개의 ndarray 객체에  int와 float가 함께 있을 수 없음
*   ndarray내의 데이터 타입은 dtype 속성으로 확인 <br> ex) list1은 integer숫자인 1,2,3을 값으로 가지고 있음, 이를 ndarray로 변경 가능

In [ ]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1,array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


*  ndarray 내의 데이터 타입은 같은 데이터 타입만 연산 가능
*  다른 데이터 유형이 섞인 list를  ndarray로 변경하면 데이터 크기가 더 큰 데이터 타입으로 형 변환 적용 <br>ex) int + string 와 int + float를 ndarray로 변경 => string으로 변경  

In [ ]:
list2 = [1,2,'test']
array2 = np.array(list2)
print(array2,array2.dtype)

list3 = [1,2,3.0]
array3 = np.array(list3)
print(array3,array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


*  astype()메서드를 이용해 ndarray 내 데이터값의 타입 변경 가능

In [ ]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float,array_float.dtype)

array_int1=array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1,2.1,3.1])
array_int2=array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


### 3) ndarray를 편리하게 생성하기 - arange, zeros, ones
특정 크기와 차원을 가진 ndarray를 연속값이나 0 또는 1로 초기화해 쉽게 생성해야할 필요가 있는 경우 사용하는 함수

*  arange() : range()와 유사한 기능, array를 range로 표현하는것,0부터 함수 인자 값 -1까지의 값을 순차적으로 ndarray의 데이터값으로 변환해 줍니다.

In [ ]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


*  zeros() : 튜플 형태의 shape값을 입력하면 모든 값을 0으로 채운 해당 shape를 가진 ndarray를 반환.
*  ones() : 튜플 형태의 shape값을 입력하면 모든 값을 1로 채운 해당 shape를 가진 ndarray를 반환. <br> 만약 dtype이 정해지지 x -> default로 float64형의 데이터로 ndarray를 채움

In [ ]:
zero_array = np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


### 4) ndarray의 차원과 크기를 변경하는 reshape
: ndarray를 특정 차원 및 크기로 변환, 이때 함수 인자는 변환을 원하는 크기

In [ ]:
array1 = np.arange(10)
print('array1:\n',array1)

array2 = array1.reshape(2,5)
print('array2:\n',array2)

array3 = array1.reshape(5,2)
print('array3:\n',array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


*  reshape()은 지정된 사이즈로 변경이 불가능하면 오류 발생

In [ ]:
array1.reshape(4,3)

ValueError: cannot reshape array of size 10 into shape (4,3)

*  reshape()은 -1을 인자로 사용하면 원래 ndarray와 호환되는 새로운 shape로 변환

In [ ]:
array1 = np.arange(10)
print(array1)
array2 = array1.reshape(-1,5)
print('array2.shape:',array2.shape)
array3 = array1.reshape(5,-1)
print('array3.shape:',array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2.shape: (2, 5)
array3.shape: (5, 2)


*   -1을 사용하더라도 호환될 수 없는 형태는 변환이 x

In [ ]:
array1 = np.arange(10)
array4 = array1.reshape(-1,4)

ValueError: cannot reshape array of size 10 into shape (4)

*  reshape(-1,1) : 원본 ndarray가 어떤 형태라도 2차원이고, 여러 개의 로우를 가지되 반드시 1개의 칼럼을 가진 ndarray로 변환됨
*  여러 개의 넘파이 ndarray는 stack이나 concat으로 결합할 때 각각의 ndarray의 형태를 통일해 유용하게 사용됨

In [ ]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n', array3d.tolist())

#3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1)
print('array5:\n', array5.tolist())
print('array5.shape:', array5.shape)

#1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print('array6:\n', array6.tolist())
print('array6.shape:', array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5.shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6.shape: (8, 1)


### 5) 넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱

-  a. 특정한 데이터만 추출
-  b. 슬라이싱
-  c. 팬시 인덱싱
-  d. 불린 인덱싱

#### 단일 값 추출
: 한 개의 데이터만을 추출하는 방법

In [ ]:
#1부터 9까지의 1차원 ndarray 생성
array1 = np.arange(start=1,stop = 10)
print('array1:',array1)

#index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터값을 의미
value = array1[2]
print('value:', value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>


*  인덱스에 마이너스 기호를 이용하면 맨 뒤에서부터 데이터 추출 가능

In [ ]:
print('맨 뒤의 값:',array1[-1],'맨 뒤에서 두 번째 값:', array1[-2])

맨 뒤의 값: 9 맨 뒤에서 두 번째 값: 8


-  단일 인덱스를 이용해 ndarray 내의 데이터 값도 간단히 수정 가능

In [ ]:
array1[0] =9
array1[8]=0
print('array1:',array1)

array1: [9 2 3 4 5 6 7 8 0]


- 다차원 ndarray에서 단일 값 추출
- axis 0: row 방향의 축
- axis 1: column 방향의 축

In [ ]:
array1d = np.arange(start=1,stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

print('(row=0,col=0) index 가리키는 값:', array2d[0,0])
print('(row=0,col=1) index 가리키는 값:', array2d[0,1])
print('(row=1,col=0) index 가리키는 값:', array2d[1,0])
print('(row=2,col=2) index 가리키는 값:', array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0,col=0) index 가리키는 값: 1
(row=0,col=1) index 가리키는 값: 2
(row=1,col=0) index 가리키는 값: 4
(row=2,col=2) index 가리키는 값: 9


#### 슬라이싱
: ':'기호를 이용해 연속한 데이터를 슬라이싱해 추출

In [ ]:
array1=np.arange(start=1,stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


- ':'사이의 시작, 종료 인덱스는 생략 가능
1. 시작 인덱스 생략: 맨 처음 인덱스인 0으로 간주
2. 종료 인덱스 생략: 맨 마지막 인덱스로 간주
3. 둘 다 생략: 맨 처음/마지막 인덱스로 간주

In [ ]:
array1 = np.arange(start=1,stop=10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


- 2차원 ndarray에서 슬라이싱으로 데이터 접근

In [ ]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print('array2d ：\n)', array2d)

print('array2d[0:2,0:2] \n', array2d[0:2,0:2])
print('array2d[1:3,0:3] \n', array2d[1:3,0:3])
print('array2d[1:3,:] \n', array2d[1:3,:])
print('array2d[:,:] \n', array2d[:,:])
print('array2d[:2,1:] \n', array2d[:2,1:])
print('array2d[:2,0] \n', array2d[:2,0])

array2d ：
) [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2,0:2] 
 [[1 2]
 [4 5]]
array2d[1:3,0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3,:] 
 [[4 5 6]
 [7 8 9]]
array2d[:,:] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2,1:] 
 [[2 3]
 [5 6]]
array2d[:2,0] 
 [1 4]


- 2차원 ndarray에서 뒤에 오는 인덱스를 없애면 1차원 ndarray 반환
- 3차원 ndarray에서 뒤에 오는 인덱스를 없애면 2차원 ndarray 반환

In [ ]:
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


#### 팬시 인덱싱
: 일정한 인덱싱 집합을 리스트 또는 ndarray형태로 지정해 해당 위치에 있는 데이터의 ndarray를 반환

In [ ]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0, 1], 2]
print('array2d[[0, 1], 2] => ', array3.tolist())

array4 = array2d[[0,1], 0:2]
print('array2d[[0,1],0:2] => ', array4.tolist())

array5 = array2d[[0,1]]
print('array2d[[0,1]] =>', array5.tolist())

array2d[[0, 1], 2] =>  [3, 6]
array2d[[0,1],0:2] =>  [[1, 2], [4, 5]]
array2d[[0,1]] => [[1, 2, 3], [4, 5, 6]]


#### 불린 인덱싱
: 특정 조건에 해당하는지 여부인 T/F값 인덱싱 집합을 기반으로 T에 해당하는 인덱스 위치에 있는 데이터의 ndarray 반환

In [ ]:
array1d = np.arange(start=1, stop=10)
# [ ] 안에 array1d > 5 Boolean indexing을 적용
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값 :', array3)

array1d > 5 불린 인덱싱 결과 값 : [6 7 8 9]


조건 필터링 과정 확인
- 넘파이 ndarray 객체에 조건식을 할당

In [ ]:
array1d >5

array([False, False, False, False, False,  True,  True,  True,  True])

- 위와 동일한 불린 ndarray를 만들고 이를 array1d[]내에 인덱스로 입력하면 동일한 데이터셋 반환

In [ ]:
boolean_indexes = np.array([False, False, False, False, False, True, True, True, True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 ：', array3)

불린 인덱스로 필터링 결과 ： [6 7 8 9]


In [ ]:
indexes = np.array([5, 6, 7, 8])
array4 = array1d[indexes]
print('일반 인덱스로 필터링 결과 :', array4)

일반 인덱스로 필터링 결과 : [6 7 8 9]


- 불린 인덱싱 동작 단계
1. ndarray의 필터링 조건을 []안에 기재
2. False값은 무시, True값에 해당하는 인덱스 값만 저장
3. 저장된 인덱스 데이터 세트로 ndarray 조회

### 6) 행렬의 정렬 - sort(), argsort()

#### 행렬 정렬
- np.sort(): 원 행렬은 유지한 채 원 행렬의 정렬된 행렬을 반환
- ndarray.sort: 원 행렬 자체를 정렬한 형태로 변환, 반환 값은 none

In [ ]:
org_array = np.array([ 3, 1, 9, 5])
print('원본 행렬:', org_array)
# np.sort( )로 정렬
sort_array1 = np.sort(org_array)
print('np.sort( ) 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort( ) 호출 후 원본 행렬:', org_array)
# ndarray.sort( )로 정렬
sort_array2 = org_array.sort()
print('org_array.sort( ) 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort( ) 호출 후 원본 행렬:', org_array)

원본 행렬: [3 1 9 5]
np.sort( ) 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort( ) 호출 후 원본 행렬: [3 1 9 5]
org_array.sort( ) 호출 후 반환된 행렬: None
org_array.sort( ) 호출 후 원본 행렬: [1 3 5 9]


- 내림 차순 정렬 : [::-1] 적용

In [ ]:
sort_array1_desc = np.sort(org_array)[::-1 ]
print ('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


- 행렬이 2차원 이상일 경우, axis 축 값 설정을 통해 row/column 방향 정렬 수행

In [ ]:
array2d = np.array([[8, 12],[7, 1]])

sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('칼럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


#### 정렬된 행렬의 인덱스 반환
np.argsort : 원본 행렬이 정렬되었을 때, 기존 원본 행렬의 원소에 대한 인덱스가 필요할 때 사용

In [ ]:
org_array = np.array([ 3, 1, 9, 5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


- 내림차순으로 정렬

In [ ]:
org_array = np.array([ 3, 1, 9, 5])
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


-  ndarray는 메타 데이터를 가질 수 없음 -> 실제 값과 그 값이 뜻하는 메타 데이터를 별도의  ndarray로 각각 가져야함

In [ ]:
import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array= np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])


성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


### 7) 선형대수 연산 - 행렬 내적과 전치 행렬 구하기

#### 행렬 내적
: 행렬 곱, np.dot을 이용해 계산 가능

In [ ]:
A = np.array( [[1, 2, 3],
[4, 5, 6]] )
B = np.array( [[7, 8],
[9, 10],
[11, 12]] )
dot_product = np.dot(A, B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


#### 전치 행렬
: 원 행렬에서 행과 열 위치를 교환한 원소로 구성한 행렬

In [ ]:
A = np.array([[1, 2],
[3, 4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
