<a href="https://colab.research.google.com/github/taehi5/Esaa_YB/blob/Week1/ESAA_YB_Week1_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
# numpy 버전 확인
print(np.__version__)

# 빌드 설정(컴파일러, blas 등) 확인
np.show_config()

2.1.3
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.13.0/lib/python3.13/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.13.0/lib/python3.13/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.13.0/lib/python3.13/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.13.0/lib/python3.13/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: ld.bfd


#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
zero_array = np.zeros(10)
print(zero_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
array = np.zeros((10,10))
# size: 전체 원소 개수, itemsize: 원소 하나가 차지하는 byte 수
print(array.size, array.itemsize)
print("%d bytes" % (array.size * array.itemsize))

100 8
800 bytes


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
array = np.zeros(10)
# index 4가 다섯번째 값
array[4] = 1
print(array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
array = np.arange(10,50)
print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
array = np.arange(10)
print('원본:', array)

# 슬라이싱 step을 -1로 주면 거꾸로 읽음
reverse_array = array[::-1]
print('뒤집은 배열:', reverse_array)

원본: [0 1 2 3 4 5 6 7 8 9]
뒤집은 배열: [9 8 7 6 5 4 3 2 1 0]


#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
array = np.arange(9)
matrix = array.reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
array = [1,2,0,0,4,0]
# 0이 아닌 원소들의 index를 반환
index = np.nonzero(array)
print(index)

(array([0, 1, 4]),)


#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [ ]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [ ]:
random_array = np.random.random((3,3,3))
print(random_array)

[[[0.12838266 0.13719585 0.32209551]
  [0.15315884 0.95516213 0.43149965]
  [0.52803422 0.89597155 0.23742023]]

 [[0.95618889 0.60302431 0.15528412]
  [0.76144997 0.68817019 0.70374812]
  [0.1349709  0.30915185 0.26523819]]

 [[0.4965228  0.06738673 0.42293327]
  [0.72241599 0.28960381 0.36234661]
  [0.45413615 0.11873962 0.32375139]]]


#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [ ]:
random_array = np.random.random((10,10))
print(random_array)

min_value = random_array.min()
max_value = random_array.max()
print('최솟값:', min_value, '최댓값:', max_value)

[[0.09188018 0.44262238 0.39161013 0.68174006 0.14156321 0.99956279
  0.62758854 0.72883508 0.49233897 0.01602011]
 [0.53481042 0.6438027  0.19782302 0.77933456 0.95345213 0.77040847
  0.68383454 0.15636111 0.96249389 0.28219515]
 [0.51610886 0.38361851 0.47804293 0.39577342 0.39282022 0.37308719
  0.56174627 0.01703633 0.57714325 0.01034259]
 [0.69490561 0.1628812  0.84284458 0.96761064 0.70034435 0.92769483
  0.30560887 0.17399668 0.33964821 0.78995464]
 [0.19719148 0.05144191 0.49240427 0.1454012  0.15504863 0.68052839
  0.19183836 0.25820344 0.3232768  0.47404607]
 [0.42730087 0.28207123 0.7412735  0.2359986  0.32424351 0.6823811
  0.20542408 0.95491311 0.05180959 0.11431924]
 [0.68646435 0.22599221 0.86584315 0.77846966 0.38097589 0.73844364
  0.03202232 0.96567893 0.27400125 0.34859467]
 [0.38563776 0.79276088 0.50576361 0.46319104 0.63006403 0.88450312
  0.25342562 0.43602202 0.60158324 0.57394936]
 [0.83714308 0.06150299 0.72972752 0.78696455 0.57856061 0.98008315
  0.51081862 

#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [ ]:
random_array = np.random.random(30)
mean_value = random_array.mean()
print('평균값:', mean_value)

평균값: 0.47671965040087644


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
array = np.ones((10,10))
# 가운데 부분만 골라서 0으로 채움
array[1:-1, 1:-1] = 0
print(array)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
# 다른 방법 : np.pad로 0으로 채운 테두리를 둘러싸기
inner = np.zeros((8,8))
array2 = np.pad(inner, pad_width=1, mode='constant', constant_values=1)
print(array2)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

nan, False, False, nan, True, False

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [ ]:
# k=-1 이면 대각선 바로 아래쪽에 값을 채움
matrix = np.diag([1,2,3,4], k=-1)
print(matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
matrix = np.zeros((8,8), dtype=int)
# 홀수 행의 짝수 열, 짝수 행의 홀수 열에 1을 채우면 체스판 무늬가 됨
matrix[1::2, ::2] = 1
matrix[::2, 1::2] = 1
print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [ ]:
index = np.unravel_index(99, (6,7,8))
print(index)

(np.int64(1), np.int64(5), np.int64(3))


#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [ ]:
matrix = np.random.random((5,5))
mean = matrix.mean()
std = matrix.std()
normalized = (matrix - mean) / std
print(normalized)

[[-1.6972844   0.66360458  0.44244452  0.6971291   0.92160543]
 [ 1.08752343  1.01100246 -0.44823107 -1.06724597  1.22910927]
 [-1.16773615  0.89750913  0.05132442 -0.72046364  0.9707895 ]
 [-1.11183104 -1.93901277  1.06078207 -1.77160309  0.76809777]
 [ 0.3293711   0.57049951  0.3570209  -1.01687685 -0.11752824]]


#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [ ]:
color_dtype = np.dtype([('r', np.ubyte),
                         ('g', np.ubyte),
                         ('b', np.ubyte),
                         ('a', np.ubyte)])
print(color_dtype)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
A = np.ones((5,3))
B = np.ones((3,2))
result = np.dot(A,B)
print(result)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [ ]:
result2 = A @ B
print(result2)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
array = np.arange(11)
print('원본:', array)

array[(array > 3) & (array < 8)] *= -1
print('변경 후:', array)

원본: [ 0  1  2  3  4  5  6  7  8  9 10]
변경 후: [ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

* Python 내장 `sum`: `sum(range(5), -1)`은 $0+1+2+3+4-1$이므로 결과가 `9`이다.
* NumPy의 `sum`: 두 번째 인수 `-1`은 시작값이 아니라 마지막 축을 의미한다. 1차원 배열에서 `axis=-1`은 유효하므로 결과가 `10`이다.

따라서 출력은 다음과 같다.

```text
9
10
```

#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z = np.arange(5)

print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
# print(Z<Z>Z) ->에러

[  1   1   4  27 256]
[0 1 2 4 8]
[False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]
[0. 1. 2. 3. 4.]


#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/tmp/ipykernel_965/3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
/tmp/ipykernel_965/3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
/tmp/ipykernel_965/3912170336.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [ ]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print('Z1:', Z1)
print('Z2:', Z2)

# 두 배열에 공통으로 들어있는 값만 뽑아줌
common = np.intersect1d(Z1,Z2)
print('공통값:', common)

Z1: [7 4 7 7 3 1 0 2 0 5]
Z2: [7 3 8 7 5 8 2 1 7 8]
공통값: [1 2 3 5 7]


#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


/tmp/ipykernel_965/2770867030.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1) == np.emath.sqrt(-1))


#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [ ]:
dates = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [ ]:
A = np.ones(3)*1
B = np.ones(3)*2

# out 파라미터를 쓰면 새로 배열을 만들지 않고 그 자리에서 계산됨
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)
print(A)

[-1.5 -1.5 -1.5]


#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [ ]:
array = np.random.uniform(0,10,10)
print('원본:', array)

# 방법1 : 나머지를 빼기
method1 = array - array%1
print('방법1:', method1)

# 방법2 : 몫 연산자 //
method2 = array // 1
print('방법2:', method2)

원본: [8.7865525  3.37764271 2.36583306 2.53438184 5.41380835 2.69368777
 1.79490878 0.02113522 2.88158415 2.15946077]
방법1: [8. 3. 2. 2. 5. 2. 1. 0. 2. 2.]
방법2: [8. 3. 2. 2. 5. 2. 1. 0. 2. 2.]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
matrix = np.zeros((5,5))
matrix += np.arange(5)
print(matrix)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 32. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
array = np.random.random(10)
print('정렬 전:', array)
array.sort()
print('정렬 후:', array)

정렬 전: [0.94575922 0.81314242 0.88852232 0.06856524 0.41397039 0.17284421
 0.02316971 0.92453648 0.42504472 0.50627515]
정렬 후: [0.02316971 0.06856524 0.17284421 0.41397039 0.42504472 0.50627515
 0.81314242 0.88852232 0.92453648 0.94575922]


#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [ ]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
print('A:', A)
print('B:', B)

is_equal = np.array_equal(A,B)
print('두 배열이 같은가?', is_equal)

A: [0 1 1 1 1]
B: [0 1 1 0 1]
두 배열이 같은가? False


#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [ ]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]

# 원점에서부터의 거리
R = np.sqrt(X**2 + Y**2)
# x축 기준 각도
T = np.arctan2(Y,X)
print('거리:', R)
print('각도:', T)

거리: [0.70230795 0.96096638 0.3257945  0.71131005 0.40229039 0.73644717
 0.37557252 1.21470766 0.80231057 1.18316324]
각도: [1.52489789 0.17528752 1.03527396 0.80935481 0.06659647 0.65568897
 0.61199518 0.77741452 0.15616449 0.59434181]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [ ]:
array = np.random.random(10)
print('원본:', array)

# argmax()로 최댓값의 index를 찾아서 그 자리를 0으로 바꿔줌
array[array.argmax()] = 0
print('변경 후:', array)

원본: [0.66356064 0.21075927 0.89564395 0.30837428 0.38020082 0.38934398
 0.43398674 0.08234681 0.38059408 0.83556491]
변경 후: [0.66356064 0.21075927 0.         0.30837428 0.38020082 0.38934398
 0.43398674 0.08234681 0.38059408 0.83556491]


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [ ]:
Z = np.arange(100)
v = np.random.uniform(0,100)
print('v:', v)

# v와 각 원소의 차이의 절댓값이 가장 작은 index를 찾음
index = (np.abs(Z-v)).argmin()
print('가장 가까운 값:', Z[index])

v: 86.72049946336664
가장 가까운 값: 87


#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [ ]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [ ]:
n = 10
p = 3
Z = np.zeros((n,n))
# n*n개의 자리 중 p개를 중복없이 뽑아서 1을 채움
Z.put(np.random.choice(range(n*n), p, replace=False), 1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 1.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [ ]:
array_3x3 = np.random.randint(0,10,(3,3))
print('원본:\n', array_3x3)

# column 3 (index 2) 기준으로 argsort한 순서대로 행을 재배열
print('column 3 기준 정렬:\n', array_3x3[array_3x3[:,2].argsort()])

원본:
 [[2 3 7]
 [5 1 2]
 [6 9 7]]
column 3 기준 정렬:
 [[5 1 2]
 [2 3 7]
 [6 9 7]]


In [ ]:
# column 2 (index 1) 기준
print('column 2 기준 정렬:\n', array_3x3[array_3x3[:,1].argsort()])

column 2 기준 정렬:
 [[5 1 2]
 [2 3 7]
 [6 9 7]]


In [ ]:
# column 1 (index 0) 기준
print('column 1 기준 정렬:\n', array_3x3[array_3x3[:,0].argsort()])

column 1 기준 정렬:
 [[2 3 7]
 [5 1 2]
 [6 9 7]]
