<a href="https://colab.research.google.com/github/taehi5/Esaa_YB/blob/Week1/YB_0904_Numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [26]:
import numpy as np

A = np.ones((5,3))
B = np.ones((3,2))
result = np.dot(A,B)

print(result)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [27]:
# 참고용 result2 = A@B
# print(result2)

#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [28]:
array = np.arange(11)
print('원본:', array )

array[(array>3)& (array < 8)] *= -1
print('변경 후 :', array)

원본: [ 0  1  2  3  4  5  6  7  8  9 10]
변경 후 : [ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

<br> 1번 : 파이썬 내장 sum의 경우 반복 가능한 값, 시작값 이라서 -1+0+1+2+3+4 = 9
<br> 2번: numpy 내장함수는 두번째 인수 -1이 마지막 축을 의미해서 axis = -1을 의미, 그래서 결과는 np.sum([0, 1, 2, 3, 4], axis=-1) = 0+1+2+3+4 = 10

#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

1. 각 원소를 자기 자신만큼 거듭제곱
2. 원소별 비트 이동
3. z < -z로 해석되는 비교
4. 1j : 허수를 의미, 정수 * 허수 = 오류 x
5. 두 번 나눗셈, 결과는 실수형
6.  파이썬&넘파이 배열 차이로 인한 오류
- 넘파이에서는 배열 연산자를 쓸 수 없어서 연속 비교가 안된다.

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

1. 0으로 나눌 수 없기 때문에 not a number // 파이썬에서는 오류 발생, np에서는 nan으로
2. //는 정수 나눗셈, 정수형에는 nan이 없음
3. nan을 정수로 잘못 표현해서 실수로 변환

In [29]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/tmp/ipykernel_703/3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
/tmp/ipykernel_703/3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
/tmp/ipykernel_703/3912170336.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [30]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)

print(Z1)
print(Z2)

common = np.intersect1d(Z1,Z2)
print(common)

[7 0 8 9 3 9 9 5 4 2]
[3 7 7 1 2 0 2 0 2 8]
[0 2 3 7 8]


#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

False. nan!=1j


In [31]:
#np.sqrt(-1) :nan // np.emath.sqrt(-1) : 입력값에 따라 복소수까지 사용해 계산하는 함수
# np. nan == 1j라는 의미 , 1j는 허수
with np.errstate(invalid="ignore"):
    print(np.sqrt(-1) == np.emath.sqrt(-1))  # False: nan != 1j

False


#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [32]:
#datetime64 = 날짜 자료형,np.arange는 시작값은 포함하지만 끝값은 포함 x
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [33]:
A = np.arange(1, 6, dtype=float)
B = np.arange(6, 11, dtype=float)

#A+B 계산해 B에 저장
np.add(A, B, out=B)
#A/2를 계산해 A에 저장
np.divide(A, 2, out=A)
#A부호를 반대로 바꾸기
np.negative(A, out=A)
#두개 결과 곱하기
np.multiply(A, B, out=A)
print(A)

[ -3.5  -9.  -16.5 -26.  -37.5]


#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [34]:
Z = np.random.uniform(0, 10, 10)
print("Original:", Z)
# 방법 1 : 나머지를 뺌
print("Method 1:", Z - Z % 1)
# 방법 2 : 몫 연산자인 // 사용
print("Method 2:", Z // 1)

Original: [5.67401196 1.69079603 6.85573375 2.30836247 3.26472362 7.0622322
 2.514382   9.98891707 0.81264084 3.87125237]
Method 1: [5. 1. 6. 2. 3. 7. 2. 9. 0. 3.]
Method 2: [5. 1. 6. 2. 3. 7. 2. 9. 0. 3.]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [35]:
# np. arange(5)이용해 1차원 배열 생성
# np.tile 이용해 주어진 배열을 반복 배치
Z = np.tile(np.arange(5), (5, 1))
print(Z)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 32. Create a random vector of size 10 and sort it (★★☆)

In [36]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.05564182 0.35394017 0.36844336 0.44075407 0.48979799 0.61418683
 0.6350597  0.67366676 0.69986789 0.78445296]


#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [37]:
# random.randint 이용해 0이상 2미만의 정수 5개 생성
# np.array_equal을 이용해 배열의 크기 및 모양이 같은지, 같은 위치의 원소가 모두 같은지 확인
A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 2, 5)
print("A:", A)
print("B:", B)
print("Equal:", np.array_equal(A, B))

A: [1 0 1 0 0]
B: [0 1 1 0 0]
Equal: False


#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [38]:
Z = np.random.random((10, 2))
x, y = Z[:, 0], Z[:, 1]
r = np.sqrt(x**2 + y**2)
theta = np.arctan2(y, x)
polar = np.column_stack((r, theta))
print(polar)  # columns: radius, angle (radians)

[[1.21668033 0.65892501]
 [0.27267189 0.73348097]
 [0.52798142 0.80978955]
 [0.89159492 0.74289743]
 [0.96719987 1.20281145]
 [1.14143231 1.03520635]
 [0.81704091 0.36822591]
 [0.86690121 0.1797495 ]
 [0.57846494 1.50344754]
 [0.51284027 0.95713155]]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [39]:
Z = np.random.random(10)
print("Before:", Z)
Z[Z.argmax()] = 0
print("After:", Z)

Before: [0.60594642 0.40005905 0.84313729 0.23739515 0.25502582 0.75312351
 0.47383335 0.45841684 0.31365707 0.70878698]
After: [0.60594642 0.40005905 0.         0.23739515 0.25502582 0.75312351
 0.47383335 0.45841684 0.31365707 0.70878698]


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [40]:
Z = np.arange(100)
v = np.random.uniform(0, 100)
closest = Z[np.abs(Z - v).argmin()]
print("v:", v)
print("Closest value:", closest)

v: 20.673369405470353
Closest value: 21


#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [41]:
Z = np.arange(9).reshape(3, 3)
for index, value in np.ndenumerate(Z):
    print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [42]:
n = 5
p = 4
Z = np.zeros((n, n), dtype=int)
np.put(Z, np.random.choice(n * n, p, replace=False), 1)
print(Z)

[[0 0 0 0 0]
 [0 0 1 0 0]
 [1 0 1 0 0]
 [0 0 0 0 0]
 [0 0 0 1 0]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [43]:
Z = np.random.randint(0, 10, (3, 3))
n = 1  # zero-based column index
print("Before:\n", Z)
Z = Z[Z[:, n].argsort()]
print(f"Sorted by column {n}:\n", Z)

Before:
 [[3 1 4]
 [8 2 9]
 [8 5 5]]
Sorted by column 1:
 [[3 1 4]
 [8 2 9]
 [8 5 5]]
